### ISSUE TITLE
Failing specs?

### ISSUE THREAD

**Issue by julien51** [jhass/open_graph_reader#4]
I wanted to investigate some weird behavior when trying to extract the URL of an OpenGraph-ed http document. I cloned the repo and run the spec... but it's failing on 36 requirements. Is that expected?

**Comment by jhass** [comment]
Mh, no. And [Travis](https://travis-ci.org/jhass/open_graph_reader) is passing. Do you still have the exact steps you took? And how are they failing?

**Comment by jhass** [comment]
Ah, nvm, I forgot that I included some fixtures as a git submodule. Run `git submodule init && git submodule update`.
